
service: crudaws-mongodb # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  stage: dev


# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:*"
      Resource:
        - "*"
# you can define service wide environment variables here
#  environment:
#    URL_DB: 52.90.145.195
#    PORT_DB: 27017

# you can add packaging information here
package:
#  include:
#    - include-me.py
#    - include-me-dir/**
   exclude:
    - env/**
    - node_modules/**
    - .vscode/**
    - requirements.txt

functions:
  trazabilidad_elastic:
    handler: trazabilidad.recibir
    layers:
    - {Ref: PythonRequirementsLambdaLayer}
  post_user:
    handler: user/post_user.post
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: user
          method: POST
          cors: true
  get_user:
    handler: user/get_user.get
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: user
          method: GET
      - http:
          path: user/{id}
          method: GET
          cors: true
          request:
            parameters:
              paths:
                id: false          
  put_user:
    handler: user/put_user.put
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: user/{id}
          method: PUT
          cors: true
          request:
            parameters:
              paths:
                id: True        
  delete_user:
    handler: user/delete_user.delete
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: user/{id}
          method: DELETE
          cors: true
          request:
            parameters:
              paths:
                id: true


custom:
  # ... for the serverless-python-requirements plugin
  pythonRequirements:
    #dockerizePip: True
    layer: True

plugins:
  - serverless-python-requirements
